
stores = {
    0 : {
        'id' : 1,
        'name' : '''Main Website
Main Website Store
Default Store View'''
    },
    1 : {
        'id' : 2,
        'name' : '''Website 2
Store Group 2 - website_id_2
Store view 2 - website_id_2 - group_id_2'''
    },
    2 : {
        'id' : 3,
        'name' : '''Website 3
Store Group 3 - website_id_3
Store view 3 - website_id_3 - group_id_3'''
    },
    3 : {
        'id' : 4,
        'name' : '''Website 4
Store Group 4 - website_id_4
Store view 4 - website_id_4 - group_id_4'''
    },
    4 : {
        'id' : 5,
        'name' : '''Website 5
Store Group 5 - website_id_5
Store view 5 - website_id_5 - group_id_5'''
    }
}

sqls = {0 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 37.0000, NULL, 37.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Best Way - Table Rate', '{customer_email}', '0', 22.0000, 15.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Best Way - Table Rate', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 37.0000, 15.0000, NULL, NULL, NULL, 0.0000, NULL, 22.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 37.0000, 15.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 22.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 22.0000, 37.0000, NULL, 0.0000, 22.0000, 37.0000, 1.0000, NULL, '{grid_increment_id}', NULL, 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'tablerate_bestway', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 15.0000, 15.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 700, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9hcmd1cy1hbGwtd2VhdGhlci10YW5rLmh0bWw,","product":"700","selected_configurable_option":"","related_product":"","item":"700","super_attribute":{"144":"168","93":"52"},"qty":"1"},"attributes_info":[{"label":"Size","value":"M","option_id":144,"option_value":"168"},{"label":"Color","value":"Gray","option_id":93,"option_value":"52"}],"simple_name":"Argus All-Weather Tank-M-Gray","simple_sku":"MT07-M-Gray","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'MT07-M-Gray', 'Argus All-Weather Tank', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 22.0000, 22.0000, 22.0000, 22.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 22.0000, 22.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 22.0000, 22.0000, 22.0000, 22.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 697, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9hcmd1cy1hbGwtd2VhdGhlci10YW5rLmh0bWw,","product":"700","selected_configurable_option":"","related_product":"","item":"700","super_attribute":{"144":"168","93":"52"},"qty":"1"}}', 1.0000, 0, 'MT07-M-Gray', 'Argus All-Weather Tank-M-Gray', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''    
},
1 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 27.0000, NULL, 27.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 22.0000, 5.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 27.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 22.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 27.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 22.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 22.0000, 27.0000, NULL, 0.0000, 22.0000, 27.0000, 1.0000, NULL, '{grid_increment_id}', '1', 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1562, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9yYWRpYW50LXRlZS5odG1s","product":"1562","selected_configurable_option":"","related_product":"","item":"1562","super_attribute":{"144":"167","93":"56"},"qty":"1"},"attributes_info":[{"label":"Size","value":"S","option_id":144,"option_value":"167"},{"label":"Color","value":"Orange","option_id":93,"option_value":"56"}],"simple_name":"Radiant Tee-S-Orange","simple_sku":"WS12-S-Orange","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'WS12-S-Orange', 'Radiant Tee', NULL, '1', NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 22.0000, 22.0000, 22.0000, 22.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 22.0000, 22.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 22.0000, 22.0000, 22.0000, 22.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1551, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9yYWRpYW50LXRlZS5odG1s","product":"1562","selected_configurable_option":"","related_product":"","item":"1562","super_attribute":{"144":"167","93":"56"},"qty":"1"}}', 1.0000, 0, 'WS12-S-Orange', 'Radiant Tee-S-Orange', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
},
2 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 39.0000, NULL, 39.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 34.0000, 5.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 39.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 34.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 39.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 34.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 34.0000, 39.0000, NULL, 0.0000, 34.0000, 39.0000, 1.0000, NULL, '{grid_increment_id}', NULL, 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1818, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9icmVhdGhlLWVhc3ktdGFuay5odG1s","product":"1818","selected_configurable_option":"","related_product":"","item":"1818","super_attribute":{"144":"167","93":"59"},"qty":"1"},"attributes_info":[{"label":"Size","value":"S","option_id":144,"option_value":"167"},{"label":"Color","value":"White","option_id":93,"option_value":"59"}],"simple_name":"Breathe-Easy Tank-S-White","simple_sku":"WT09-S-White","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'WT09-S-White', 'Breathe-Easy Tank', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 34.0000, 34.0000, 34.0000, 34.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 34.0000, 34.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 34.0000, 34.0000, 34.0000, 34.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1807, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9icmVhdGhlLWVhc3ktdGFuay5odG1s","product":"1818","selected_configurable_option":"","related_product":"","item":"1818","super_attribute":{"144":"167","93":"59"},"qty":"1"}}', 1.0000, 0, 'WT09-S-White', 'Breathe-Easy Tank-S-White', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
},
3 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 64.0000, NULL, 64.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 59.0000, 5.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 64.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 59.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 64.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 59.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 59.0000, 64.0000, NULL, 0.0000, 59.0000, 64.0000, 0.0000, NULL, '{grid_increment_id}', '2', 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 6, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9mdXNpb24tYmFja3BhY2suaHRtbA,,","product":"6","selected_configurable_option":"","related_product":"","item":"6","qty":"1"}}', NULL, 0, '24-MB02', 'Fusion Backpack', NULL, '2', NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 59.0000, 59.0000, 59.0000, 59.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 59.0000, 59.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, 59.0000, 59.0000, 59.0000, 59.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : ""
},
4 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 51.0000, NULL, 51.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 46.0000, 5.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 51.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 46.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 51.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 46.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 46.0000, 51.0000, NULL, 0.0000, 46.0000, 51.0000, 1.0000, NULL, '{grid_increment_id}', NULL, 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 756, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC92aWt0b3ItbHVtYXRlY2gtdHJhZGUtcGFudC5odG1s","product":"756","selected_configurable_option":"","related_product":"","item":"756","super_attribute":{"144":"176","93":"50"},"qty":"1"},"attributes_info":[{"label":"Size","value":"33","option_id":144,"option_value":"176"},{"label":"Color","value":"Blue","option_id":93,"option_value":"50"}],"simple_name":"Viktor LumaTech&trade; Pant-33-Blue","simple_sku":"MP02-33-Blue","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'MP02-33-Blue', 'Viktor LumaTech&trade; Pant', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 46.0000, 46.0000, 46.0000, 46.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 46.0000, 46.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 46.0000, 46.0000, 46.0000, 46.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 747, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC92aWt0b3ItbHVtYXRlY2gtdHJhZGUtcGFudC5odG1s","product":"756","selected_configurable_option":"","related_product":"","item":"756","super_attribute":{"144":"176","93":"50"},"qty":"1"}}', 1.0000, 0, 'MP02-33-Blue', 'Viktor LumaTech&trade; Pant-33-Blue', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
},
5 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 54.0000, NULL, 54.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Best Way - Table Rate', '{customer_email}', '0', 39.0000, 15.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Best Way - Table Rate', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 54.0000, 15.0000, NULL, NULL, NULL, 0.0000, NULL, 39.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 54.0000, 15.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 39.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 39.0000, 54.0000, NULL, 0.0000, 39.0000, 54.0000, 1.0000, NULL, '{grid_increment_id}', NULL, 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'tablerate_bestway', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 15.0000, 15.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1738, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9ub25hLWZpdG5lc3MtdGFuay5odG1s","product":"1738","selected_configurable_option":"","related_product":"","item":"1738","super_attribute":{"144":"167","93":"58"},"qty":"1"},"attributes_info":[{"label":"Size","value":"S","option_id":144,"option_value":"167"},{"label":"Color","value":"Red","option_id":93,"option_value":"58"}],"simple_name":"Nona Fitness Tank-S-Red","simple_sku":"WT04-S-Red","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'WT04-S-Red', 'Nona Fitness Tank', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 39.0000, 39.0000, 39.0000, 39.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 39.0000, 39.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 39.0000, 39.0000, 39.0000, 39.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1728, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9ub25hLWZpdG5lc3MtdGFuay5odG1s","product":"1738","selected_configurable_option":"","related_product":"","item":"1738","super_attribute":{"144":"167","93":"58"},"qty":"1"}}', 1.0000, 0, 'WT04-S-Red', 'Nona Fitness Tank-S-Red', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
},
6 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 82.0000, NULL, 82.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 77.0000, 5.0000, '{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 82.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 77.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 82.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 77.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 77.0000, 82.0000, NULL, 0.0000, 77.0000, 82.0000, 1.0000, NULL, '{grid_increment_id}', '2', 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1402, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9vbGl2aWEtMS00LXppcC1saWdodC1qYWNrZXQuaHRtbA,,","product":"1402","selected_configurable_option":"","related_product":"","item":"1402","super_attribute":{"144":"167","93":"49"},"qty":"1"},"attributes_info":[{"label":"Size","value":"S","option_id":144,"option_value":"167"},{"label":"Color","value":"Black","option_id":93,"option_value":"49"}],"simple_name":"Olivia 1\\/4 Zip Light Jacket-S-Black","simple_sku":"WJ12-S-Black","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'WJ12-S-Black', 'Olivia 1/4 Zip Light Jacket', NULL, '2', NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 77.0000, 77.0000, 77.0000, 77.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 77.0000, 77.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, 77.0000, 77.0000, 77.0000, 77.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1390, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9vbGl2aWEtMS00LXppcC1saWdodC1qYWNrZXQuaHRtbA,,","product":"1402","selected_configurable_option":"","related_product":"","item":"1402","super_attribute":{"144":"167","93":"49"},"qty":"1"}}', 1.0000, 0, 'WJ12-S-Black', 'Olivia 1/4 Zip Light Jacket-S-Black', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
},
7 : {
    "grid" : '''INSERT INTO ya_sample_store.sales_order_grid
(entity_id, status, store_id, store_name, customer_id, base_grand_total, base_total_paid, grand_total, total_paid, increment_id, base_currency_code, order_currency_code, shipping_name, billing_name, created_at, updated_at, billing_address, shipping_address, shipping_information, customer_email, customer_group, subtotal, shipping_and_handling, customer_name, payment_method, total_refunded, pickup_location_code, shipping_location)
VALUES({grid_entity_id}, 'pending', {store_id}, '{store_name}', NULL, 47.0000, NULL, 47.0000, NULL, '{grid_increment_id}', 'RUB', 'RUB', '{customer_name}', '{customer_name}', STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), '{billing_address}', '{shipping_address}', 'Flat Rate - Fixed', '{customer_email}', '0', 42.0000, 5.0000,'{customer_name}', 'checkmo', NULL, '{pickup_location_code}', '{shipping_location}');
''',
    "order" : '''INSERT INTO ya_sample_store.sales_order
(entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, customer_dob, increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, gift_message_id, paypal_ipn_customer_notified)
VALUES({grid_entity_id}, 'new', 'pending', NULL, '{protection_code}', 'Flat Rate - Fixed', 0, {store_id}, NULL, 0.0000, NULL, NULL, NULL, 47.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 42.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 1.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, 47.0000, 5.0000, NULL, NULL, NULL, 0.0000, NULL, 0.0000, 0.0000, 42.0000, NULL, NULL, NULL, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1.0000, NULL, NULL, NULL, 1, 1, {next_p2_item_item_id}, 0, NULL, NULL, 1, NULL, NULL, NULL, {grid_entity_id}, {next_p1_item_item_id}, NULL, NULL, NULL, NULL, 0.0000, 42.0000, 47.0000, NULL, 0.0000, 42.0000, 47.0000, 1.0000, NULL, '{grid_increment_id}', NULL, 'RUB', '{customer_email}', '{customer_first_name}', '{customer_lastname}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'RUB', NULL, NULL, 'RUB', NULL, NULL, NULL, NULL, NULL, '{ip_address}', 'flatrate_flatrate', 'RUB', '{store_name}', NULL, NULL, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1, NULL, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, 5.0000, 5.0000, NULL, NULL, 0);
    ''',
    "item_1" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({item_item_id}, {grid_entity_id}, NULL, {item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1895, 'configurable', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9zeWx2aWEtY2FwcmkuaHRtbA,,","product":"1895","selected_configurable_option":"","related_product":"","item":"1895","super_attribute":{"144":"172","93":"50"},"qty":"1"},"attributes_info":[{"label":"Size","value":"29","option_id":144,"option_value":"172"},{"label":"Color","value":"Blue","option_id":93,"option_value":"50"}],"simple_name":"Sylvia Capri-29-Blue","simple_sku":"WP11-29-Blue","product_calculations":1,"shipment_type":0}', 1.0000, 0, 'WP11-29-Blue', 'Sylvia Capri', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 42.0000, 42.0000, 42.0000, 42.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 42.0000, 42.0000, 0.0000, 0.0000, 1.0000, NULL, NULL, NULL, NULL, NULL, 42.0000, 42.0000, 42.0000, 42.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
''',
    "item_2" : '''INSERT INTO ya_sample_store.sales_order_item
(item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_decimal, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, gift_message_id, gift_message_available, free_shipping, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition)
VALUES({next_item_item_id}, {grid_entity_id}, {item_item_id}, {next_item_item_id}, 1, STR_TO_DATE('{created_at}', '%Y-%m-%d %T'), STR_TO_DATE('{updated_at}', '%Y-%m-%d %T'), 1892, 'simple', '{"info_buyRequest":{"uenc":"aHR0cDovL3lhLXNhbXBsZS1zdG9yZS5sb2NhbC9zeWx2aWEtY2FwcmkuaHRtbA,,","product":"1895","selected_configurable_option":"","related_product":"","item":"1895","super_attribute":{"144":"172","93":"50"},"qty":"1"}}', 1.0000, 0, 'WP11-29-Blue', 'Sylvia Capri-29-Blue', NULL, NULL, NULL, 0, 0, NULL, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, NULL, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
'''
}}
